//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Sctipts/UI/MenuInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MenuInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MenuInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MenuInput"",
    ""maps"": [
        {
            ""name"": ""AnyKey"",
            ""id"": ""a93faeeb-56b1-4171-9c18-f0aadbd430cf"",
            ""actions"": [
                {
                    ""name"": ""anykey"",
                    ""type"": ""Button"",
                    ""id"": ""66babe32-e478-4715-b797-6d2f51fe8b05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6a2daa69-0193-41f7-ba04-a9452a809324"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""anykey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // AnyKey
        m_AnyKey = asset.FindActionMap("AnyKey", throwIfNotFound: true);
        m_AnyKey_anykey = m_AnyKey.FindAction("anykey", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AnyKey
    private readonly InputActionMap m_AnyKey;
    private List<IAnyKeyActions> m_AnyKeyActionsCallbackInterfaces = new List<IAnyKeyActions>();
    private readonly InputAction m_AnyKey_anykey;
    public struct AnyKeyActions
    {
        private @MenuInput m_Wrapper;
        public AnyKeyActions(@MenuInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @anykey => m_Wrapper.m_AnyKey_anykey;
        public InputActionMap Get() { return m_Wrapper.m_AnyKey; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AnyKeyActions set) { return set.Get(); }
        public void AddCallbacks(IAnyKeyActions instance)
        {
            if (instance == null || m_Wrapper.m_AnyKeyActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AnyKeyActionsCallbackInterfaces.Add(instance);
            @anykey.started += instance.OnAnykey;
            @anykey.performed += instance.OnAnykey;
            @anykey.canceled += instance.OnAnykey;
        }

        private void UnregisterCallbacks(IAnyKeyActions instance)
        {
            @anykey.started -= instance.OnAnykey;
            @anykey.performed -= instance.OnAnykey;
            @anykey.canceled -= instance.OnAnykey;
        }

        public void RemoveCallbacks(IAnyKeyActions instance)
        {
            if (m_Wrapper.m_AnyKeyActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAnyKeyActions instance)
        {
            foreach (var item in m_Wrapper.m_AnyKeyActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AnyKeyActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AnyKeyActions @AnyKey => new AnyKeyActions(this);
    public interface IAnyKeyActions
    {
        void OnAnykey(InputAction.CallbackContext context);
    }
}
